#!/bin/ksh
#
# Alexei Znamensky <russoz@gmail.com>
#

base_dir=/my/control/bin
start_seq="dmgr-ctl node-ctl server1-ctl"
stop_seq="server1-ctl node-ctl dmgr-ctl"

##############################################################################

msg() {
  echo "$@" >&2
}

usage() {
  msg "usage: ALL-ctl (start|stop|kill|restart)"
  exit 1
}

cmd="$1"; shift
[ -z "$cmd" ] && usage
err=0

case "$cmd" in
  start)
    msg "=== Attempting to $cmd services: $start_seq"
    for s in $start_seq; do
      ${base_dir}/${s} start || { msg "ERROR: Cannot start: ${s}"; err=1 }
    done; return $err ;;

  stop|kill)
    msg "=== Attempting to $cmd services: $stop_seq"
    for s in $stop_seq; do
      ${base_dir}/${s} ${cmd} || { msg "ERROR: Cannot ${cmd}: ${s}"; err=1 }
    done; return $err ;;

  restart)
    $0 stop || $0 kill || {
      msg "ERROR: Failed to stop services. Aborting."; return 1
    }
    msg "Sleeping for a minute"; sleep 60
    $0 start ;;

  *) usage ;;
esac

